### ISSUE TITLE
Create API component 

### ISSUE THREAD

**Issue by JorgeGarciaIrazabal** [jaune/eoapi#2]
The API component will be the root element with the basic information that applies to the whole API

properties that have to be included

```
  description: ""
  version: ""
  title: ""
  termsOfService: ""
  contact:
    email: ""
  license:
    name: ""
    url: ""
host: ""
basePath: "/"
tags:
- name: ""
  description: ""
  externalDocs:
    description: ""
    url: ""
schemes:
```
