### ISSUE TITLE
Create Security Definitions

### ISSUE THREAD

**Issue by JorgeGarciaIrazabal** [jaune/eoapi#3]
describes what authentification and authorization are implemented in the API:
```
securityDefinitions:
  petstore_auth:
    type: ""
    authorizationUrl: ""
    flow: ""
    scopes:
      write:pets: ""
      read:pets: ""
  api_key:
    type: ""
    name: ""
    in: ""
```
